{% set name = "imod" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc51ce7305d3d1e6d0675ce652d1af8ac7423e8c88963f2caeefe92db2c5177d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - rasterio >=1.0
    - geopandas
    - scikit-image
    - numpy
    - numba
    - scipy
    - xarray >=0.11
    - cftime >=1.0
    - pandas
    - dask
    - affine
    - jinja2
    - cytoolz
    - toolz

test:
  imports:
    - imod

about:
  home: https://gitlab.com/deltares/imod/imod-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Work with iMOD MODFLOW models'

  description: |
    The imod Python package is an addition to iMOD and iMODFLOW, intended to facilitate
    working with groundwater models from Python. It does this by supporting reading and
    writing of the different iMOD file formats to existing objects often used in Python
    data processing.
  doc_url: https://deltares.gitlab.io/imod/imod-python/
  dev_url: https://gitlab.com/deltares/imod/imod-python

extra:
  recipe-maintainers:
    - visr
    - Huite
